;; A palindromic number reads the same both ways. The largest palindrome made
;; from the product of two 2-digit numbers is 9009 = 91 × 99.

;; Find the largest palindrome made from the product of two 3-digit numbers.

(require '[clojure.string :as s])

(defn three-digit-numbers []
  (vec (range 999 100 -1)))

(defn all-pairs [seq1 seq2]
  (for [x seq1 y seq2] (vector x y)))

(defn cartesian-multiplication-map
  "Given two sequences, generate the sequence generated by multiplying each
  element in seq1 with each element in seq2"
  [seq1 seq2]
  (map #(* (first %) (second %)) (all-pairs seq1 seq2)))

(defn sorted-cartesian-mult-map [seq1 seq2]
  (reverse (sort (cartesian-multiplication-map seq1 seq2))))

(defn palindrome? [x]
  (let [strx (str x)
        reverse-strx (s/reverse strx)]
  (= strx reverse-strx)))

(defn problem-4 []
  (first (drop-while
          (comp not palindrome?)
          (sorted-cartesian-mult-map (three-digit-numbers) (three-digit-numbers)))))

(comment
  (problem-4)
)
